import 'package:flutter/material.dart';
import 'package:show_trade/core/constTypes/const_color.dart';

TextTheme lightTextTheme = TextTheme(
  displayLarge: TextStyle(
    inherit: true,
    color: Colors.black,
    backgroundColor: Colors.transparent,
    fontSize: 57,
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    letterSpacing: -0.25,
    wordSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
    height: 1.12,
    leadingDistribution: TextLeadingDistribution.even,
    locale: Locale('en', 'US'),
    shadows: [],
    fontFeatures: [],
    decoration: TextDecoration.none,
    decorationColor: Colors.black,
    decorationStyle: TextDecorationStyle.solid,
    decorationThickness: 1,
    debugLabel: 'displayLarge',
    fontFamily: 'Roboto',
    overflow: TextOverflow.clip,
  ),
  displayMedium: TextStyle(
    inherit: true,
    color: Colors.black,
    fontSize: 45,
    fontWeight: FontWeight.w400,
    letterSpacing: -0.25,
    height: 1.16,
  ),
  displaySmall: TextStyle(
    //inherit: true,
    color: policy_text_color,
    fontSize: 36,
    fontWeight: FontWeight.w700,
    letterSpacing: 0,
   
  ),

  // Headline Styles
  headlineLarge: TextStyle(
    inherit: true,
    color: Colors.black,
    fontSize: 32,
    fontWeight: FontWeight.w400,
    letterSpacing: -0.25,
    height: 1.25,
  ),
  headlineMedium: TextStyle(
    inherit: true,
    color: policy_text_color,
    fontSize: 28,
    fontWeight: FontWeight.w600,
    letterSpacing: -0.25,
    height: 1.29,
  ),
  headlineSmall: TextStyle(
    inherit: true,
    color: Colors.black,
    fontSize: 24,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    height: 1.33,
  ),

  // Title Styles
  titleLarge: TextStyle(
    inherit: true,
    color: Colors.black,
    fontSize: 22,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    height: 1.27,
  ),
  titleMedium: TextStyle(
    inherit: true,
    color: policy_text_color,
    fontSize: 16,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.15,
    height: 1.5,
  ),
  titleSmall: TextStyle(
    inherit: true,
    color: Colors.black,
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    height: 1.43,
  ),

  // Body Styles
  bodyLarge: TextStyle(
    inherit: true,
    color: policy_text_color,
    //backgroundColor: const Color.fromARGB(0, 250, 3, 3),
    fontSize: 16,
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    letterSpacing: 0.5,
    wordSpacing: 0,
    textBaseline: TextBaseline.alphabetic,
    height: 1.5,
    leadingDistribution: TextLeadingDistribution.even,
    locale: Locale('en', 'US'),
    shadows: [],
    fontFeatures: [],
    decoration: TextDecoration.none,
    decorationColor: Colors.black,
    decorationStyle: TextDecorationStyle.solid,
    decorationThickness: 1,
    debugLabel: 'bodyLarge',
    fontFamily: 'Roboto',
    overflow: TextOverflow.clip,
  ),
  bodyMedium: TextStyle(
    inherit: true,
    color: policy_text_color,
    fontSize: 16,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.43,
  ),
  bodySmall: TextStyle(
    inherit: true,
    color: Colors.black,
    fontSize: 12,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.4,
    height: 1.33,
  ),

  // Label Styles
  labelLarge: TextStyle(
    inherit: true,
    color: Colors.black,
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    height: 1.43,
  ),
  labelMedium: TextStyle(
    inherit: true,
    color: Colors.black,
    fontSize: 12,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.5,
    height: 1.33,
  ),
  labelSmall: TextStyle(
    inherit: true,
    color: Colors.black,
    fontSize: 11,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.5,
    height: 1.45,
  ),
);