// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJJiBtCFRHYO1okUNctrMkU04xXr7FGoE',
    appId: '1:285591308576:web:ebfe017fa32ca48a70af45',
    messagingSenderId: '285591308576',
    projectId: 'showtrade-42b19',
    authDomain: 'showtrade-42b19.firebaseapp.com',
    storageBucket: 'showtrade-42b19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlmPS7C8ZXCcoINa1QiCkd_sbqTWkLAUs',
    appId: '1:285591308576:android:0efed22cf1f3001370af45',
    messagingSenderId: '285591308576',
    projectId: 'showtrade-42b19',
    storageBucket: 'showtrade-42b19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE4wXjyzTMHUnsQOe6u65fcjaDLI7aY1Y',
    appId: '1:285591308576:ios:cf79bf9360c8d25170af45',
    messagingSenderId: '285591308576',
    projectId: 'showtrade-42b19',
    storageBucket: 'showtrade-42b19.firebasestorage.app',
    iosBundleId: 'com.example.showTrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE4wXjyzTMHUnsQOe6u65fcjaDLI7aY1Y',
    appId: '1:285591308576:ios:cf79bf9360c8d25170af45',
    messagingSenderId: '285591308576',
    projectId: 'showtrade-42b19',
    storageBucket: 'showtrade-42b19.firebasestorage.app',
    iosBundleId: 'com.example.showTrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJJiBtCFRHYO1okUNctrMkU04xXr7FGoE',
    appId: '1:285591308576:web:1a5bae840f9b9fc970af45',
    messagingSenderId: '285591308576',
    projectId: 'showtrade-42b19',
    authDomain: 'showtrade-42b19.firebaseapp.com',
    storageBucket: 'showtrade-42b19.firebasestorage.app',
  );
}
